spring:
  application:
    name: iamserver
  datasource:
    url: jdbc:postgresql://localhost:16850/db_iam
    username: itpusr
    password: itp@168
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 9090